[[pages]]
path = "pages/1_main_page.py"
name = "Main Page"
icon = "ğŸ—ºï¸"
url_path = "main-page"

[[pages]]
path = "pages/2_upload_data.py"
name = "Upload Data"
icon = "ğŸ“¤"
url_path = "upload-data-page"

[[pages]]
path = "pages/3_about_me.py"
name = "About Me"
icon = "â„¹ï¸"
url_path = "about-me-page"